      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ backend_app_name }}-{{ target_backend_env }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ backend_app_name }}"
          env: "{{ target_backend_env }}"
          version: "{{ version_backend }}"
      spec:
        replicas: "{{ replicas }}"
        selector:
          matchLabels:
            app: "{{ backend_app_name }}"
            env: "{{ target_backend_env }}"
        template:
          metadata:
            labels:
              app: "{{ backend_app_name }}"
              env: "{{ target_backend_env }}"
              version: "{{ version_backend }}"
          spec:
            containers:
              - name: "{{ backend_app_name }}"
                image: "{{ app_host }}:{{ nodeport_registry }}/metrics-api:{{ version_backend }}"
                ports:
                  - containerPort: 5000
                env:
                  - name: PROMETHEUS_URL
                    value: "{{ prometheus_url }}"
                readinessProbe:
                  httpGet:
                    path: /
                    port: 5000
                  initialDelaySeconds: 10
                  periodSeconds: 5
                livenessProbe:
                  httpGet:
                    path: /
                    port: 5000
                  initialDelaySeconds: 30
                  periodSeconds: 10
                resources:
                  requests:
                    memory: "64Mi"
                    cpu: "64m"
                  limits:
                    memory: "128Mi"
                    cpu: "128m"