      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ frontend_app_name }}-service-{{ target_frontend_env }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          app: "{{ frontend_app_name }}"
          env: "{{ target_frontend_env }}"
        ports:
          - port: 3000
            targetPort: 3000
        type: ClusterIP